@api_server=https://api.github.com
@owner=praneetdhoolia
@repo=langgraph-se-agent
@path=src/se_agent


### get_file_contents
GET {{api_server}}/repos/{{owner}}/{{repo}}/contents/{{path}} HTTP/1.1
Authorization: Bearer {{GH_TOKEN}}
Content-Type: application/json
Accept: application/vnd.github.v3+json
